allowBuilds:
  '@applemusic-like-lyrics/core': true
  '@applemusic-like-lyrics/lyric': true
  '@applemusic-like-lyrics/vue': true
  '@swc/core': true
  esbuild: true
patchedDependencies:
  vite-plugin-top-level-await@1.6.0: patches/vite-plugin-top-level-await@1.6.0.patch
